location: applications
sources:
  - repo: git://git.suckless.org/dwm
    name: dwm
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -

  - repo: https://github.com/supercrabtree/k
    name: zsh/plugins/k
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -

  - repo: https://github.com/junegunn/fzf.git
    name: zsh/plugins/fzf
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -
default_group: ''
groups:
  -
